export const Permissions = {
  // ViewPersonalProfile: { key: 'ViewPersonalProfile', label: 'View personal profile' },
  ViewPersonalProfile: 'View personal profile',
  ViewContacts: 'View contacts',
  ViewSalaryAndDocumentsData: 'View salary and documents data',
  EditFullEmployeesData: 'Edit full employees data',
  AccessAnalyticalForecastsPage: 'access to analytical forecasts page',
  ViewAccounts: 'View accounts',
  EditAccounts: 'Edit accounts',
  ViewRoles: 'View roles',
  EditRoles: 'Edit roles',
  CanManageTenants: 'Can Manage Tenants',
  IsTenantsHardDeleteAllowed: 'Is Tenants Hard Delete Allowed',
  CanRequestCompensations: 'Can Request Compensations',
  CanManageCompensations: 'Can Manage Compensations',
  CanManageDocuments: 'Can Manage Documents',
};
